# Generated by Django 2.1.4 on 2018-12-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=3)),
                ('param1', models.IntegerField()),
                ('param2', models.IntegerField()),
            ],
        ),
    ]
